package:
  name: stride
  version: '0.0.2a'

source:
  path: ../

build:
  preserve_egg_dir: True

requirements:
  build:
    - python ==3.8
    - setuptools
    - pip
    - cython
    - numpy >=1.20.3
    - gensim ==3.8.3
    - scikit-learn >=0.24
    - wheel >=0.36.2
    - pandas >=1.1.4
    - scipy >=1.6.3
    - matplotlib >=3.3.3
    - seaborn >=0.11.1
    - scanpy >=1.6.0
    - h5py >=2.10.0
    - pytables
    - pot >=0.7.0
    - xlrd ==1.2.0
  run:
    - python ==3.8
    - setuptools
    - pip
    - cython
    - numpy >=1.20.3
    - gensim ==3.8.3
    - scikit-learn >=0.24
    - wheel >=0.36.2
    - pandas >=1.1.4
    - scipy >=1.6.3
    - matplotlib >=3.3.3
    - seaborn >=0.11.1
    - scanpy >=1.6.0
    - h5py >=2.10.0
    - pytables
    - pot >=0.7.0
    - xlrd ==1.2.0

about:
  home: https://github.com/DongqingSun96/STRIDE
  license: GPL-3.0
  summary: STRIDE (Spatial TRanscrIptomics DEconvolution by topic modelling) is a cell-type deconvolution tool for spatial transcriptomics using scRNA-seq. 
